; The MIT License (MIT)
;
; Copyright (c) 2015 Microsoft
; 
; Permission is hereby granted, free of charge, to any person obtaining a copy
; of this software and associated documentation files (the "Software"), to deal
; in the Software without restriction, including without limitation the rights
; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
; copies of the Software, and to permit persons to whom the Software is
; furnished to do so, subject to the following conditions:
;
; The above copyright notice and this permission notice shall be included in all
; copies or substantial portions of the Software.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
; SOFTWARE.

.code
win_asm_forwSequentialRead_Word128 proc

; Arguments:
; rcx is address of the first 128-bit word in the array
; rdx is address of the last 128-bit word in the array

; rax holds current 128-bit word address
; ymm0 holds result from reading the memory 128-bit wide

	mov rax,rcx		; initialize current word address to start of the array
	cmp rax,rdx		; have we reached the last word yet?
	jae done		; if current word address is >= last word address, jump to done

myloop:
	; Unroll 256 loads of 128-bit words (16 bytes is 10h) before checking loop condition.
	vmovdqa xmm0, xmmword ptr [rax+0000h]				
	vmovdqa xmm0, xmmword ptr [rax+0010h]
	vmovdqa xmm0, xmmword ptr [rax+0020h]
	vmovdqa xmm0, xmmword ptr [rax+0030h]
	vmovdqa xmm0, xmmword ptr [rax+0040h]
	vmovdqa xmm0, xmmword ptr [rax+0050h]
	vmovdqa xmm0, xmmword ptr [rax+0060h]
	vmovdqa xmm0, xmmword ptr [rax+0070h]
	vmovdqa xmm0, xmmword ptr [rax+0080h]
	vmovdqa xmm0, xmmword ptr [rax+0090h]
	vmovdqa xmm0, xmmword ptr [rax+00A0h]
	vmovdqa xmm0, xmmword ptr [rax+00B0h]
	vmovdqa xmm0, xmmword ptr [rax+00C0h]
	vmovdqa xmm0, xmmword ptr [rax+00D0h]
	vmovdqa xmm0, xmmword ptr [rax+00E0h]
	vmovdqa xmm0, xmmword ptr [rax+00F0h]
	vmovdqa xmm0, xmmword ptr [rax+0100h]			
	vmovdqa xmm0, xmmword ptr [rax+0110h]
	vmovdqa xmm0, xmmword ptr [rax+0120h]
	vmovdqa xmm0, xmmword ptr [rax+0130h]
	vmovdqa xmm0, xmmword ptr [rax+0140h]
	vmovdqa xmm0, xmmword ptr [rax+0150h]
	vmovdqa xmm0, xmmword ptr [rax+0160h]
	vmovdqa xmm0, xmmword ptr [rax+0170h]
	vmovdqa xmm0, xmmword ptr [rax+0180h]
	vmovdqa xmm0, xmmword ptr [rax+0190h]
	vmovdqa xmm0, xmmword ptr [rax+01A0h]
	vmovdqa xmm0, xmmword ptr [rax+01B0h]
	vmovdqa xmm0, xmmword ptr [rax+01C0h]
	vmovdqa xmm0, xmmword ptr [rax+01D0h]
	vmovdqa xmm0, xmmword ptr [rax+01E0h]
	vmovdqa xmm0, xmmword ptr [rax+01F0h]
	vmovdqa xmm0, xmmword ptr [rax+0200h]			
	vmovdqa xmm0, xmmword ptr [rax+0210h]
	vmovdqa xmm0, xmmword ptr [rax+0220h]
	vmovdqa xmm0, xmmword ptr [rax+0230h]
	vmovdqa xmm0, xmmword ptr [rax+0240h]
	vmovdqa xmm0, xmmword ptr [rax+0250h]
	vmovdqa xmm0, xmmword ptr [rax+0260h]
	vmovdqa xmm0, xmmword ptr [rax+0270h]
	vmovdqa xmm0, xmmword ptr [rax+0280h]
	vmovdqa xmm0, xmmword ptr [rax+0290h]
	vmovdqa xmm0, xmmword ptr [rax+02A0h]
	vmovdqa xmm0, xmmword ptr [rax+02B0h]
	vmovdqa xmm0, xmmword ptr [rax+02C0h]
	vmovdqa xmm0, xmmword ptr [rax+02D0h]
	vmovdqa xmm0, xmmword ptr [rax+02E0h]
	vmovdqa xmm0, xmmword ptr [rax+02F0h]
	vmovdqa xmm0, xmmword ptr [rax+0300h]			
	vmovdqa xmm0, xmmword ptr [rax+0310h]
	vmovdqa xmm0, xmmword ptr [rax+0320h]
	vmovdqa xmm0, xmmword ptr [rax+0330h]
	vmovdqa xmm0, xmmword ptr [rax+0340h]
	vmovdqa xmm0, xmmword ptr [rax+0350h]
	vmovdqa xmm0, xmmword ptr [rax+0360h]
	vmovdqa xmm0, xmmword ptr [rax+0370h]
	vmovdqa xmm0, xmmword ptr [rax+0380h]
	vmovdqa xmm0, xmmword ptr [rax+0390h]
	vmovdqa xmm0, xmmword ptr [rax+03A0h]
	vmovdqa xmm0, xmmword ptr [rax+03B0h]
	vmovdqa xmm0, xmmword ptr [rax+03C0h]
	vmovdqa xmm0, xmmword ptr [rax+03D0h]
	vmovdqa xmm0, xmmword ptr [rax+03E0h]
	vmovdqa xmm0, xmmword ptr [rax+03F0h]
	vmovdqa xmm0, xmmword ptr [rax+0400h]			
	vmovdqa xmm0, xmmword ptr [rax+0410h]
	vmovdqa xmm0, xmmword ptr [rax+0420h]
	vmovdqa xmm0, xmmword ptr [rax+0430h]
	vmovdqa xmm0, xmmword ptr [rax+0440h]
	vmovdqa xmm0, xmmword ptr [rax+0450h]
	vmovdqa xmm0, xmmword ptr [rax+0460h]
	vmovdqa xmm0, xmmword ptr [rax+0470h]
	vmovdqa xmm0, xmmword ptr [rax+0480h]
	vmovdqa xmm0, xmmword ptr [rax+0490h]
	vmovdqa xmm0, xmmword ptr [rax+04A0h]
	vmovdqa xmm0, xmmword ptr [rax+04B0h]
	vmovdqa xmm0, xmmword ptr [rax+04C0h]
	vmovdqa xmm0, xmmword ptr [rax+04D0h]
	vmovdqa xmm0, xmmword ptr [rax+04E0h]
	vmovdqa xmm0, xmmword ptr [rax+04F0h]
	vmovdqa xmm0, xmmword ptr [rax+0500h]			
	vmovdqa xmm0, xmmword ptr [rax+0510h]
	vmovdqa xmm0, xmmword ptr [rax+0520h]
	vmovdqa xmm0, xmmword ptr [rax+0530h]
	vmovdqa xmm0, xmmword ptr [rax+0540h]
	vmovdqa xmm0, xmmword ptr [rax+0550h]
	vmovdqa xmm0, xmmword ptr [rax+0560h]
	vmovdqa xmm0, xmmword ptr [rax+0570h]
	vmovdqa xmm0, xmmword ptr [rax+0580h]
	vmovdqa xmm0, xmmword ptr [rax+0590h]
	vmovdqa xmm0, xmmword ptr [rax+05A0h]
	vmovdqa xmm0, xmmword ptr [rax+05B0h]
	vmovdqa xmm0, xmmword ptr [rax+05C0h]
	vmovdqa xmm0, xmmword ptr [rax+05D0h]
	vmovdqa xmm0, xmmword ptr [rax+05E0h]
	vmovdqa xmm0, xmmword ptr [rax+05F0h]
	vmovdqa xmm0, xmmword ptr [rax+0600h]			
	vmovdqa xmm0, xmmword ptr [rax+0610h]
	vmovdqa xmm0, xmmword ptr [rax+0620h]
	vmovdqa xmm0, xmmword ptr [rax+0630h]
	vmovdqa xmm0, xmmword ptr [rax+0640h]
	vmovdqa xmm0, xmmword ptr [rax+0650h]
	vmovdqa xmm0, xmmword ptr [rax+0660h]
	vmovdqa xmm0, xmmword ptr [rax+0670h]
	vmovdqa xmm0, xmmword ptr [rax+0680h]
	vmovdqa xmm0, xmmword ptr [rax+0690h]
	vmovdqa xmm0, xmmword ptr [rax+06A0h]
	vmovdqa xmm0, xmmword ptr [rax+06B0h]
	vmovdqa xmm0, xmmword ptr [rax+06C0h]
	vmovdqa xmm0, xmmword ptr [rax+06D0h]
	vmovdqa xmm0, xmmword ptr [rax+06E0h]
	vmovdqa xmm0, xmmword ptr [rax+06F0h]
	vmovdqa xmm0, xmmword ptr [rax+0700h]			
	vmovdqa xmm0, xmmword ptr [rax+0710h]
	vmovdqa xmm0, xmmword ptr [rax+0720h]
	vmovdqa xmm0, xmmword ptr [rax+0730h]
	vmovdqa xmm0, xmmword ptr [rax+0740h]
	vmovdqa xmm0, xmmword ptr [rax+0750h]
	vmovdqa xmm0, xmmword ptr [rax+0760h]
	vmovdqa xmm0, xmmword ptr [rax+0770h]
	vmovdqa xmm0, xmmword ptr [rax+0780h]
	vmovdqa xmm0, xmmword ptr [rax+0790h]
	vmovdqa xmm0, xmmword ptr [rax+07A0h]
	vmovdqa xmm0, xmmword ptr [rax+07B0h]
	vmovdqa xmm0, xmmword ptr [rax+07C0h]
	vmovdqa xmm0, xmmword ptr [rax+07D0h]
	vmovdqa xmm0, xmmword ptr [rax+07E0h]
	vmovdqa xmm0, xmmword ptr [rax+07F0h]
	vmovdqa xmm0, xmmword ptr [rax+0800h]
	vmovdqa xmm0, xmmword ptr [rax+0810h]
	vmovdqa xmm0, xmmword ptr [rax+0820h]
	vmovdqa xmm0, xmmword ptr [rax+0830h]
	vmovdqa xmm0, xmmword ptr [rax+0840h]
	vmovdqa xmm0, xmmword ptr [rax+0850h]
	vmovdqa xmm0, xmmword ptr [rax+0860h]
	vmovdqa xmm0, xmmword ptr [rax+0870h]
	vmovdqa xmm0, xmmword ptr [rax+0880h]
	vmovdqa xmm0, xmmword ptr [rax+0890h]
	vmovdqa xmm0, xmmword ptr [rax+08A0h]
	vmovdqa xmm0, xmmword ptr [rax+08B0h]
	vmovdqa xmm0, xmmword ptr [rax+08C0h]
	vmovdqa xmm0, xmmword ptr [rax+08D0h]
	vmovdqa xmm0, xmmword ptr [rax+08E0h]
	vmovdqa xmm0, xmmword ptr [rax+08F0h]
	vmovdqa xmm0, xmmword ptr [rax+0900h]			
	vmovdqa xmm0, xmmword ptr [rax+0910h]
	vmovdqa xmm0, xmmword ptr [rax+0920h]
	vmovdqa xmm0, xmmword ptr [rax+0930h]
	vmovdqa xmm0, xmmword ptr [rax+0940h]
	vmovdqa xmm0, xmmword ptr [rax+0950h]
	vmovdqa xmm0, xmmword ptr [rax+0960h]
	vmovdqa xmm0, xmmword ptr [rax+0970h]
	vmovdqa xmm0, xmmword ptr [rax+0980h]
	vmovdqa xmm0, xmmword ptr [rax+0990h]
	vmovdqa xmm0, xmmword ptr [rax+09A0h]
	vmovdqa xmm0, xmmword ptr [rax+09B0h]
	vmovdqa xmm0, xmmword ptr [rax+09C0h]
	vmovdqa xmm0, xmmword ptr [rax+09D0h]
	vmovdqa xmm0, xmmword ptr [rax+09E0h]
	vmovdqa xmm0, xmmword ptr [rax+09F0h]
	vmovdqa xmm0, xmmword ptr [rax+0A00h]			
	vmovdqa xmm0, xmmword ptr [rax+0A10h]
	vmovdqa xmm0, xmmword ptr [rax+0A20h]
	vmovdqa xmm0, xmmword ptr [rax+0A30h]
	vmovdqa xmm0, xmmword ptr [rax+0A40h]
	vmovdqa xmm0, xmmword ptr [rax+0A50h]
	vmovdqa xmm0, xmmword ptr [rax+0A60h]
	vmovdqa xmm0, xmmword ptr [rax+0A70h]
	vmovdqa xmm0, xmmword ptr [rax+0A80h]
	vmovdqa xmm0, xmmword ptr [rax+0A90h]
	vmovdqa xmm0, xmmword ptr [rax+0AA0h]
	vmovdqa xmm0, xmmword ptr [rax+0AB0h]
	vmovdqa xmm0, xmmword ptr [rax+0AC0h]
	vmovdqa xmm0, xmmword ptr [rax+0AD0h]
	vmovdqa xmm0, xmmword ptr [rax+0AE0h]
	vmovdqa xmm0, xmmword ptr [rax+0AF0h]
	vmovdqa xmm0, xmmword ptr [rax+0B00h]			
	vmovdqa xmm0, xmmword ptr [rax+0B10h]
	vmovdqa xmm0, xmmword ptr [rax+0B20h]
	vmovdqa xmm0, xmmword ptr [rax+0B30h]
	vmovdqa xmm0, xmmword ptr [rax+0B40h]
	vmovdqa xmm0, xmmword ptr [rax+0B50h]
	vmovdqa xmm0, xmmword ptr [rax+0B60h]
	vmovdqa xmm0, xmmword ptr [rax+0B70h]
	vmovdqa xmm0, xmmword ptr [rax+0B80h]
	vmovdqa xmm0, xmmword ptr [rax+0B90h]
	vmovdqa xmm0, xmmword ptr [rax+0BA0h]
	vmovdqa xmm0, xmmword ptr [rax+0BB0h]
	vmovdqa xmm0, xmmword ptr [rax+0BC0h]
	vmovdqa xmm0, xmmword ptr [rax+0BD0h]
	vmovdqa xmm0, xmmword ptr [rax+0BE0h]
	vmovdqa xmm0, xmmword ptr [rax+0BF0h]
	vmovdqa xmm0, xmmword ptr [rax+0C00h]			
	vmovdqa xmm0, xmmword ptr [rax+0C10h]
	vmovdqa xmm0, xmmword ptr [rax+0C20h]
	vmovdqa xmm0, xmmword ptr [rax+0C30h]
	vmovdqa xmm0, xmmword ptr [rax+0C40h]
	vmovdqa xmm0, xmmword ptr [rax+0C50h]
	vmovdqa xmm0, xmmword ptr [rax+0C60h]
	vmovdqa xmm0, xmmword ptr [rax+0C70h]
	vmovdqa xmm0, xmmword ptr [rax+0C80h]
	vmovdqa xmm0, xmmword ptr [rax+0C90h]
	vmovdqa xmm0, xmmword ptr [rax+0CA0h]
	vmovdqa xmm0, xmmword ptr [rax+0CB0h]
	vmovdqa xmm0, xmmword ptr [rax+0CC0h]
	vmovdqa xmm0, xmmword ptr [rax+0CD0h]
	vmovdqa xmm0, xmmword ptr [rax+0CE0h]
	vmovdqa xmm0, xmmword ptr [rax+0CF0h]
	vmovdqa xmm0, xmmword ptr [rax+0D00h]			
	vmovdqa xmm0, xmmword ptr [rax+0D10h]
	vmovdqa xmm0, xmmword ptr [rax+0D20h]
	vmovdqa xmm0, xmmword ptr [rax+0D30h]
	vmovdqa xmm0, xmmword ptr [rax+0D40h]
	vmovdqa xmm0, xmmword ptr [rax+0D50h]
	vmovdqa xmm0, xmmword ptr [rax+0D60h]
	vmovdqa xmm0, xmmword ptr [rax+0D70h]
	vmovdqa xmm0, xmmword ptr [rax+0D80h]
	vmovdqa xmm0, xmmword ptr [rax+0D90h]
	vmovdqa xmm0, xmmword ptr [rax+0DA0h]
	vmovdqa xmm0, xmmword ptr [rax+0DB0h]
	vmovdqa xmm0, xmmword ptr [rax+0DC0h]
	vmovdqa xmm0, xmmword ptr [rax+0DD0h]
	vmovdqa xmm0, xmmword ptr [rax+0DE0h]
	vmovdqa xmm0, xmmword ptr [rax+0DF0h]
	vmovdqa xmm0, xmmword ptr [rax+0E00h]			
	vmovdqa xmm0, xmmword ptr [rax+0E10h]
	vmovdqa xmm0, xmmword ptr [rax+0E20h]
	vmovdqa xmm0, xmmword ptr [rax+0E30h]
	vmovdqa xmm0, xmmword ptr [rax+0E40h]
	vmovdqa xmm0, xmmword ptr [rax+0E50h]
	vmovdqa xmm0, xmmword ptr [rax+0E60h]
	vmovdqa xmm0, xmmword ptr [rax+0E70h]
	vmovdqa xmm0, xmmword ptr [rax+0E80h]
	vmovdqa xmm0, xmmword ptr [rax+0E90h]
	vmovdqa xmm0, xmmword ptr [rax+0EA0h]
	vmovdqa xmm0, xmmword ptr [rax+0EB0h]
	vmovdqa xmm0, xmmword ptr [rax+0EC0h]
	vmovdqa xmm0, xmmword ptr [rax+0ED0h]
	vmovdqa xmm0, xmmword ptr [rax+0EE0h]
	vmovdqa xmm0, xmmword ptr [rax+0EF0h]
	vmovdqa xmm0, xmmword ptr [rax+0F00h]			
	vmovdqa xmm0, xmmword ptr [rax+0F10h]
	vmovdqa xmm0, xmmword ptr [rax+0F20h]
	vmovdqa xmm0, xmmword ptr [rax+0F30h]
	vmovdqa xmm0, xmmword ptr [rax+0F40h]
	vmovdqa xmm0, xmmword ptr [rax+0F50h]
	vmovdqa xmm0, xmmword ptr [rax+0F60h]
	vmovdqa xmm0, xmmword ptr [rax+0F70h]
	vmovdqa xmm0, xmmword ptr [rax+0F80h]
	vmovdqa xmm0, xmmword ptr [rax+0F90h]
	vmovdqa xmm0, xmmword ptr [rax+0FA0h]
	vmovdqa xmm0, xmmword ptr [rax+0FB0h]
	vmovdqa xmm0, xmmword ptr [rax+0FC0h]
	vmovdqa xmm0, xmmword ptr [rax+0FD0h]
	vmovdqa xmm0, xmmword ptr [rax+0FE0h]
	vmovdqa xmm0, xmmword ptr [rax+0FF0h]

	add rax,1000h							; End of one unrolled loop iteration. Increment pointer by 256 words of size 16 bytes, which is 4096 bytes.
	
	cmp rax,rdx		; have we reached the last word yet?
	jae done		; if current word address is >= last word address, jump to done
	jmp myloop		; continue loop

done:
	xor eax,eax		; return 0
	ret

win_asm_forwSequentialRead_Word128 endp
end
